name: flutter_app
description: Stock Alert Mobile App - Flutter Version
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  file_picker: ^8.0.0
  path_provider: ^2.1.0
  web_socket_channel: ^3.0.3
  dio: ^5.9.0
  logger: ^2.6.2
  equatable: ^2.0.8
  intl: ^0.20.2
  permission_handler: ^11.3.1
  share_plus: ^10.1.3
  workmanager: ^0.9.0+3
  flutter_local_notifications: ^19.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/models/
